### ISSUE TITLE
Are expandable tables working?

### ISSUE THREAD

**Issue by johnpitchko** [justboil/bulma-responsive-tables#13]
Really interested in the expandable table, however I could neither see them work on the demo page nor have them work in my local app. Perhaps there is something missing?

**Comment by DMunkei** [comment]
I believe, you need to write the logic yourself using JS/jQuery? I'm thinking of a possible way to get this working.  
Maybe, when clicking onto the chevron, you can extract the information in the other `td` elements and create a new node...? Then when closing it again, you end up deleting it again? Seems like a hassle though.
Other than that, nice work with the responsive tables. Hats off.
